#!/usr/bin/env python3
"""
Post-hoc DeepConf analysis from offline SFT traces.

This script reads `deepthink_offline_qid*.pkl` files (e.g. generated by
`sft_inference.sh` with budget=320) and computes:

1) DeepConf-online style sweep (post-hoc simulation)
   - warmup_traces=32 (configurable)
   - no consensus stop
   - adaptive group length per question: round(mean_trace_len / divisor)
   - sweep confidence thresholds derived from warmup traces
   - report token usage + accuracy trade-off

2) DeepConf-offline confidence subsets over repeated 256-subsamples
   - most-confidence accuracy
   - top 5% confidence accuracy
   - top 10% confidence accuracy

Output is a JSON file that can be visualized by PreCoT helper
`PreCoT/visualize_deepconf_sweep.py`.
"""

from __future__ import annotations

import argparse
import json
import math
import pickle
import random
import re
from collections import defaultdict
from pathlib import Path
from statistics import mean
from typing import Any, Dict, List, Optional, Tuple

try:
    from dynasor.core.evaluator import math_equal as _math_equal
except Exception:
    _math_equal = None


OFFLINE_PATTERN = re.compile(
    r"^deepthink_offline_qid(?P<qid>\d+)_rid(?P<rid>.+)_(?P<ts>\d{8}_\d{6})\.pkl$"
)


def quick_parse(text: str) -> str:
    if text is None:
        return ""
    out = str(text)
    while "\\text{" in out:
        start = out.find("\\text{")
        if start < 0:
            break
        end = out.find("}", start)
        if end < 0:
            break
        content = out[start + 6 : end]
        out = out[:start] + content + out[end + 1 :]
    return out


def equal_func(answer: str, ground_truth: str) -> bool:
    a = quick_parse(answer).strip()
    g = str(ground_truth).strip()
    if len(a) == 1 and a.isalpha() and len(g) == 1 and g.isalpha():
        return a.lower() == g.lower()
    if _math_equal is not None:
        try:
            return bool(_math_equal(a, g))
        except Exception:
            pass
    return a == g


def parse_filename(path: Path) -> Optional[Tuple[int, str, str]]:
    m = OFFLINE_PATTERN.match(path.name)
    if not m:
        return None
    return int(m.group("qid")), m.group("rid"), m.group("ts")


def load_ground_truth_map(dataset_path: Optional[Path]) -> Dict[int, str]:
    if dataset_path is None:
        return {}
    gt_map: Dict[int, str] = {}
    with dataset_path.open("r", encoding="utf-8") as f:
        for qid, line in enumerate(f):
            line = line.strip()
            if not line:
                continue
            record = json.loads(line)
            gt_map[qid] = str(record.get("answer", "")).strip()
    return gt_map


def pick_latest_files(
    results_dir: Path,
    rid_filter: Optional[str],
    max_qid: Optional[int],
) -> Dict[int, Path]:
    by_qid: Dict[int, Tuple[str, Path]] = {}

    for pkl_path in sorted(results_dir.glob("deepthink_offline_qid*_rid*.pkl")):
        parsed = parse_filename(pkl_path)
        if parsed is None:
            continue
        qid, rid, ts = parsed
        if max_qid is not None and qid > max_qid:
            continue
        if rid_filter and rid != rid_filter:
            continue
        current = by_qid.get(qid)
        if current is None or ts > current[0]:
            by_qid[qid] = (ts, pkl_path)

    return {qid: item[1] for qid, item in by_qid.items()}


def token_count(trace: Dict[str, Any]) -> int:
    if isinstance(trace.get("num_tokens"), int):
        return max(0, int(trace["num_tokens"]))
    token_ids = trace.get("token_ids")
    if isinstance(token_ids, list):
        return len(token_ids)
    confs = trace.get("confs")
    if isinstance(confs, list):
        return len(confs)
    return 0


def adaptive_group_size(traces: List[Dict[str, Any]], divisor: float) -> int:
    lengths = [token_count(t) for t in traces if token_count(t) > 0]
    if not lengths:
        return 1
    mean_len = float(mean(lengths))
    group = int(round(mean_len / divisor))
    return max(1, group)


def min_group_conf(trace: Dict[str, Any], group_size: int) -> float:
    confs = trace.get("confs") or []
    if not confs:
        return float("inf")
    if len(confs) < group_size:
        return float(np.mean(confs))

    window_sum = sum(confs[:group_size])
    best = window_sum / group_size
    for idx in range(group_size, len(confs)):
        window_sum += confs[idx] - confs[idx - group_size]
        mean_val = window_sum / group_size
        if mean_val < best:
            best = mean_val
    return float(best)


def stop_token_count(
    trace: Dict[str, Any],
    threshold: float,
    group_size: int,
) -> int:
    confs = trace.get("confs") or []
    full_tokens = token_count(trace)
    if not confs or full_tokens <= 0:
        return full_tokens

    if len(confs) < group_size:
        return full_tokens

    window_sum = sum(confs[:group_size])
    if window_sum / group_size < threshold:
        return min(full_tokens, group_size)

    for idx in range(group_size, len(confs)):
        window_sum += confs[idx] - confs[idx - group_size]
        if window_sum / group_size < threshold:
            # EOS is enforced at this step in the real online processor.
            return min(full_tokens, idx + 1)

    return full_tokens


def simple_majority_vote(answers: List[str]) -> Optional[str]:
    if not answers:
        return None
    counts: Dict[str, int] = defaultdict(int)
    for answer in answers:
        counts[str(answer)] += 1
    return max(counts.items(), key=lambda x: x[1])[0]


def evaluate_answer(pred: Optional[str], gt: str) -> bool:
    if pred is None:
        return False
    try:
        return equal_func(str(pred), gt)
    except Exception:
        return str(pred).strip() == str(gt).strip()


def trace_answer(trace: Dict[str, Any]) -> Optional[str]:
    ans = trace.get("extracted_answer")
    if ans is None:
        return None
    ans_str = str(ans).strip()
    return ans_str if ans_str else None


def quantile_thresholds(values: List[float], points: int) -> List[float]:
    uniq = sorted(set(float(v) for v in values if math.isfinite(float(v))))
    if not uniq:
        return []
    if points <= 1:
        mid = len(uniq) // 2
        if len(uniq) % 2 == 1:
            return [float(uniq[mid])]
        return [float((uniq[mid - 1] + uniq[mid]) / 2.0)]

    def quantile_linear(sorted_values: List[float], q: float) -> float:
        if q <= 0.0:
            return float(sorted_values[0])
        if q >= 1.0:
            return float(sorted_values[-1])
        pos = q * (len(sorted_values) - 1)
        lo = int(math.floor(pos))
        hi = int(math.ceil(pos))
        if lo == hi:
            return float(sorted_values[lo])
        frac = pos - lo
        return float(sorted_values[lo] * (1.0 - frac) + sorted_values[hi] * frac)

    quantiles = [i / (points - 1) for i in range(points)]
    return [quantile_linear(uniq, q) for q in quantiles]


def run_online_sweep_for_question(
    traces: List[Dict[str, Any]],
    ground_truth: str,
    qid: int,
    rng: random.Random,
    warmup_traces: int,
    total_budget: int,
    sweep_points: int,
    adaptive_divisor: float,
    resamples: int,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if len(traces) < max(2, warmup_traces + 1):
        return rows

    budget = min(total_budget, len(traces))

    for sample_id in range(resamples):
        picked_idx = rng.sample(range(len(traces)), budget)
        picked = [traces[i] for i in picked_idx]
        rng.shuffle(picked)

        warm = picked[:warmup_traces]
        final = picked[warmup_traces:]
        if not warm or not final:
            continue

        group_size = adaptive_group_size(picked, adaptive_divisor)
        warm_scores = [min_group_conf(t, group_size) for t in warm]
        thresholds = quantile_thresholds(warm_scores, sweep_points)
        if not thresholds:
            continue

        warm_scores_map = [min_group_conf(t, group_size) for t in warm]
        final_scores_map = [min_group_conf(t, group_size) for t in final]
        full_tokens = sum(token_count(t) for t in picked)
        warm_tokens = sum(token_count(t) for t in warm)

        for sweep_idx, threshold in enumerate(thresholds):
            voting_answers: List[str] = []

            # Warmup traces contribute only when score >= threshold
            for trace, score in zip(warm, warm_scores_map):
                ans = trace_answer(trace)
                if ans is not None and score >= threshold:
                    voting_answers.append(ans)

            final_tokens = 0
            stopped_final = 0
            for trace, score in zip(final, final_scores_map):
                final_tokens += stop_token_count(trace, threshold, group_size)
                if score < threshold:
                    stopped_final += 1
                    continue
                ans = trace_answer(trace)
                if ans is not None:
                    voting_answers.append(ans)

            pred = simple_majority_vote(voting_answers)
            is_correct = evaluate_answer(pred, ground_truth)
            total_tokens = warm_tokens + final_tokens
            answer_rate = 1.0 if pred is not None else 0.0
            token_ratio = (total_tokens / full_tokens) if full_tokens > 0 else 0.0

            rows.append(
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "sweep_index": sweep_idx,
                    "threshold": threshold,
                    "group_size": group_size,
                    "warmup_used": len(warm),
                    "final_used": len(final),
                    "final_stopped": stopped_final,
                    "total_tokens": int(total_tokens),
                    "full_tokens": int(full_tokens),
                    "token_ratio": float(token_ratio),
                    "has_prediction": bool(pred is not None),
                    "is_correct": bool(is_correct),
                }
            )

    return rows


def run_offline_confidence_for_question(
    traces: List[Dict[str, Any]],
    ground_truth: str,
    qid: int,
    rng: random.Random,
    sample_size: int,
    adaptive_divisor: float,
    resamples: int,
) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    if len(traces) < 2:
        return rows

    n = min(sample_size, len(traces))

    for sample_id in range(resamples):
        picked_idx = rng.sample(range(len(traces)), n)
        picked = [traces[i] for i in picked_idx]

        group_size = adaptive_group_size(picked, adaptive_divisor)
        valid = []
        for trace in picked:
            ans = trace_answer(trace)
            if ans is None:
                continue
            score = min_group_conf(trace, group_size)
            valid.append((score, ans))

        if not valid:
            rows.append(
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "most_confidence",
                    "has_prediction": False,
                    "is_correct": False,
                }
            )
            rows.append(
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "top5_confidence",
                    "has_prediction": False,
                    "is_correct": False,
                }
            )
            rows.append(
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "top10_confidence",
                    "has_prediction": False,
                    "is_correct": False,
                }
            )
            continue

        valid.sort(key=lambda x: x[0])  # lower min_conf -> higher confidence

        def vote_top(frac: float) -> Optional[str]:
            k = max(1, int(math.ceil(len(valid) * frac)))
            answers = [ans for _, ans in valid[:k]]
            return simple_majority_vote(answers)

        pred_most = valid[0][1]
        pred_top5 = vote_top(0.05)
        pred_top10 = vote_top(0.10)

        rows.extend(
            [
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "most_confidence",
                    "has_prediction": pred_most is not None,
                    "is_correct": evaluate_answer(pred_most, ground_truth),
                },
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "top5_confidence",
                    "has_prediction": pred_top5 is not None,
                    "is_correct": evaluate_answer(pred_top5, ground_truth),
                },
                {
                    "qid": qid,
                    "sample_id": sample_id,
                    "group_size": group_size,
                    "method": "top10_confidence",
                    "has_prediction": pred_top10 is not None,
                    "is_correct": evaluate_answer(pred_top10, ground_truth),
                },
            ]
        )

    return rows


def aggregate_online(rows: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    by_sweep: Dict[int, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_sweep[int(row["sweep_index"])].append(row)

    summary: List[Dict[str, Any]] = []
    for sweep_idx in sorted(by_sweep.keys()):
        group = by_sweep[sweep_idx]
        summary.append(
            {
                "sweep_index": sweep_idx,
                "cases": len(group),
                "mean_threshold": float(mean([g["threshold"] for g in group])),
                "mean_group_size": float(mean([g["group_size"] for g in group])),
                "mean_tokens": float(mean([g["total_tokens"] for g in group])),
                "mean_token_ratio": float(mean([g["token_ratio"] for g in group])),
                "accuracy": float(mean([1.0 if g["is_correct"] else 0.0 for g in group])),
                "answer_rate": float(mean([1.0 if g["has_prediction"] else 0.0 for g in group])),
            }
        )
    return summary


def aggregate_offline(rows: List[Dict[str, Any]]) -> Dict[str, Dict[str, float]]:
    by_method: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_method[str(row["method"])].append(row)

    summary: Dict[str, Dict[str, float]] = {}
    for method, group in by_method.items():
        summary[method] = {
            "cases": float(len(group)),
            "accuracy": float(mean([1.0 if g["is_correct"] else 0.0 for g in group])),
            "answer_rate": float(mean([1.0 if g["has_prediction"] else 0.0 for g in group])),
            "mean_group_size": float(mean([g["group_size"] for g in group])),
        }
    return summary


def main() -> None:
    parser = argparse.ArgumentParser(description="Analyze DeepConf from SFT offline traces.")
    parser.add_argument("--results_dir", required=True, help="Directory with deepthink_offline_qid*.pkl files")
    parser.add_argument("--dataset", default=None, help="Optional JSONL dataset for fallback ground truth")
    parser.add_argument("--rid", default=None, help="Use only this run id")
    parser.add_argument("--max_qid", type=int, default=None, help="Optional qid upper bound")
    parser.add_argument("--output_json", default="deepconf_sft_analysis.json", help="Where to save analysis JSON")

    parser.add_argument("--online_warmup_traces", type=int, default=32)
    parser.add_argument("--online_total_budget", type=int, default=320)
    parser.add_argument("--online_sweep_points", type=int, default=16)
    parser.add_argument("--online_resamples", type=int, default=1)

    parser.add_argument("--offline_sample_size", type=int, default=256)
    parser.add_argument("--offline_resamples", type=int, default=30)

    parser.add_argument("--adaptive_divisor", type=float, default=10.0, help="group_size = round(mean_len / adaptive_divisor)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--keep_per_case", action="store_true", help="Store per-case rows in output JSON")

    args = parser.parse_args()

    results_dir = Path(args.results_dir)
    if not results_dir.exists():
        raise FileNotFoundError(f"results_dir not found: {results_dir}")

    dataset_map = load_ground_truth_map(Path(args.dataset) if args.dataset else None)
    latest_files = pick_latest_files(results_dir, args.rid, args.max_qid)
    if not latest_files:
        raise FileNotFoundError(
            f"No matching deepthink_offline_qid*.pkl found in: {results_dir}"
        )

    print(f"Found {len(latest_files)} qids to analyze.")

    rng = random.Random(args.seed)
    online_rows: List[Dict[str, Any]] = []
    offline_rows: List[Dict[str, Any]] = []
    skipped_qids: List[int] = []

    for qid in sorted(latest_files.keys()):
        pkl_path = latest_files[qid]
        with pkl_path.open("rb") as f:
            data = pickle.load(f)

        traces = data.get("all_traces") or []
        if not traces:
            skipped_qids.append(qid)
            continue

        gt = str(data.get("ground_truth", "")).strip()
        if not gt:
            gt = dataset_map.get(qid, "")
        if not gt:
            skipped_qids.append(qid)
            continue

        online_rows.extend(
            run_online_sweep_for_question(
                traces=traces,
                ground_truth=gt,
                qid=qid,
                rng=rng,
                warmup_traces=args.online_warmup_traces,
                total_budget=args.online_total_budget,
                sweep_points=args.online_sweep_points,
                adaptive_divisor=args.adaptive_divisor,
                resamples=args.online_resamples,
            )
        )

        offline_rows.extend(
            run_offline_confidence_for_question(
                traces=traces,
                ground_truth=gt,
                qid=qid,
                rng=rng,
                sample_size=args.offline_sample_size,
                adaptive_divisor=args.adaptive_divisor,
                resamples=args.offline_resamples,
            )
        )

    online_summary = aggregate_online(online_rows)
    offline_summary = aggregate_offline(offline_rows)

    output = {
        "config": {
            "results_dir": str(results_dir),
            "dataset": args.dataset,
            "rid": args.rid,
            "max_qid": args.max_qid,
            "seed": args.seed,
            "online_warmup_traces": args.online_warmup_traces,
            "online_total_budget": args.online_total_budget,
            "online_sweep_points": args.online_sweep_points,
            "online_resamples": args.online_resamples,
            "offline_sample_size": args.offline_sample_size,
            "offline_resamples": args.offline_resamples,
            "adaptive_divisor": args.adaptive_divisor,
            "consensus_stop_used": False,
        },
        "summary": {
            "num_qids_loaded": len(latest_files),
            "num_qids_skipped": len(skipped_qids),
            "skipped_qids": skipped_qids,
            "online_rows": len(online_rows),
            "offline_rows": len(offline_rows),
        },
        "online_sweep": {
            "aggregate": online_summary,
        },
        "offline_confidence": {
            "aggregate": offline_summary,
        },
    }

    if args.keep_per_case:
        output["online_sweep"]["per_case"] = online_rows
        output["offline_confidence"]["per_case"] = offline_rows

    output_path = Path(args.output_json)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump(output, f, indent=2)

    print(f"Saved analysis JSON: {output_path}")
    if online_summary:
        best_acc = max(online_summary, key=lambda x: x["accuracy"])
        print(
            "Online best accuracy sweep index="
            f"{best_acc['sweep_index']} acc={best_acc['accuracy']:.4f} "
            f"token_ratio={best_acc['mean_token_ratio']:.4f}"
        )
    if offline_summary:
        for method in ["most_confidence", "top5_confidence", "top10_confidence"]:
            stats = offline_summary.get(method)
            if stats:
                print(f"Offline {method}: accuracy={stats['accuracy']:.4f}")


if __name__ == "__main__":
    main()
